### ISSUE TITLE
Video Files of rundown editor demo

### ISSUE THREAD

**Issue by nyok92** [SuperFlyTV/sofie-automation-rundown-editor#44]
Hello, in the demo rundown for rundown editor there is some video files and graphics references, where could we find them ? Is there some place to download them ? Where do I need to put them on my local hard drive ?  If I want to create a new rundown what is the way to reference them with the path on my harddisk ? Should it be done by package manager ?
Thanks for any help.

**Comment by alvancamp** [comment]
Hello @nyok92!

We've just updated the [demo blueprints README](https://github.com/SuperFlyTV/sofie-demo-blueprints/blob/master/README.md) with a link to the [Sofie Demo Assets](https://superfly.tv/sofie/demo/assets/sofie-demo-assets_v1.1.0.zip) along with instructions on where to put them (in your CasparCG Server folder) and how to configure CasparCG to serve them. We've also released [a new version of the demo blueprints](https://github.com/SuperFlyTV/sofie-demo-blueprints/releases/tag/0.4.0) which includes Package Manager support as well as vMix support. Please note that as of writing, you'll need to be using Package Manager release39 in order for things to function as expected (it is currently compatible with Sofie Core release37).

If you want to create a new rundown, the paths you reference will be relative to your CasparCG `<media-path>`.

In the demo setup, Package Manager will only check that the expected files are present in your CasparCG media path. It will not place those files there for you. It will, however, generate previews and thumbnails that get used in the Sofie Core UI. These previews and thumbnails will be placed alongside the other files in your CasparCG media path.

In addition, we've just released [a new version of the Rundown Editor](https://github.com/SuperFlyTV/sofie-automation-rundown-editor/releases/tag/v1.2.0) which makes it easier to re-ingest a rundown after changes to the blueprints have been made. Check out the [updated README](https://github.com/SuperFlyTV/sofie-automation-rundown-editor/blob/master/README.md) for instructions.

Please let us know if you have any further questions or run into any issues!

**Comment by nyok92** [comment]
Hello @alvancamp !

Thanks for the tips. 
I managed to get rundown playing , i see video playing on PGM but still have issues with the Package manager (tried with the v37 release and tried the v39 too by building exe on windows).
In packacgge status, everything is at 0% :
 new:Can't read the Package from PackageContainer "CasparCG Package Container" (on accessor "CasparCG HTTP Proxy Accessor"), due to: Got error code 404 when trying to fetch package
waiting:2 workers available, about to start...

The build for release 39 github branch of package manager shows another version on sofie coresystem status: 
Package manager: check expectedVersion.@sofie-automation/server-core-integration: Version mismatch: Device "Package manager" version: "1.38.0-nightly-release38-20211208-162831-102085a.0" does not satisfy expected version range of @sofie-automation/server-core-integration: "~1.37.0-0" (Device has to be updated)


About Lower thirds: Do i have to create a L3d for casparcg ? Could i put some HTML/Js ones (edit names and fonctions with the rundown editor)

**Comment by alvancamp** [comment]
@nyok92 when you have Package Manager running, are you able to access http://localhost:8080/packages? That URL should return a JSON list of all the packages that Package Manager sees in the `basePath`. If not, then it's possible that something else on that computer is already using port 8080. To check, you can use Windows' built-in Resource Monitor utility to see which programs are listening on which ports:

![Untitled](https://user-images.githubusercontent.com/873012/150804195-a102c7e3-bf9a-4f68-89bf-e300f5540fa3.png)

Regarding lowerthirds: the Sofie Demo Assets zip comes with a lowerthird (as well as other graphics, all located in the `sofie-demo-template` folder), so you can use that for demo purposes. If you'd like to provide your own lowerthird, then yes you'd be making it for CasparCG and yes it supports HTML/JS templates.

**Comment by alvancamp** [comment]
@nyok92 what is the full command that you are using to start Package Manager? Does it have the correct `--basePath` argument? It should be the path to your CasparCG media folder, which in the demo setup should be something like this:

```bash
yarn start:single-app -- -- --basePath "C:\Your\Path\To\CasparCG Server\sofie-demo-media"
```

As for lowerthirds, I just checked the demo assets zip file and you're right, I made a mistake and only zipped up the `sofie-demo-media` folder and completely excluded the `sofie-demo-template` folder. I've fixed my mistake and uploaded a version 1.1.1 of the sofie demo assets zip here: https://superfly.tv/sofie/demo/assets/sofie-demo-assets_v1.1.1.zip

**Comment by nyok92** [comment]
@alvancamp Hello, i just reinstalled agin everythin and it's working now. I have my preview video files in rundown, and casparcg is playing files.
I just often have "casparcg0: CasparCG disconnected" alerts but what is strange is that play orders from sofie are still taken by casparcg, and it still playing videofiles.

**Comment by alvancamp** [comment]
I'm closing this issue for now, but please feel free to leave another comment or open another issue if you run into any further problems!
